### ISSUE TITLE
Channel UX

### ISSUE THREAD

**Issue by KnowledgeGarden** [topicquests/sensecraft#116]
Channels, in general, constitute a root conversation node, then other child nodes according to the conversation's purpose. A typical purpose is that of a particular Role.

Leadership is a particular role - one that's welded to the infrastructure.
All other roles are dynamically defined by guild leadership. For instance, a Guild with just 5 members, say, doesn't need to break up into any roles; a Guild with 50 members, to stay within the Dunbar suggested limit of 5 per conversation, would need 10 or so roles.

But, each channel needs a particular UX.

This task will explore, essentially, the same kind of UX being applied to the actual generation of game moves.

**Comment by KnowledgeGarden** [comment]
A feature which defines dynamically-allocated addressable UX means that there will need to be a way to **dispatch** - something like routing - established. What this really means is that there needs to be a kind of SDK for guild admins which allows them to define "roles" (channels) and make them available to role players - guild members. 
In theory, a menu of available role rooms (channels) would be made available, but once a guild member is assigned to a particular role, that, and only that role room becomes available to that member.

**Comment by KnowledgeGarden** [comment]
So, this issue #115 is almost solely one of working out the UX, and not the plumbing, wiring, and routing necessary to make it usable.  We know that the leadership route will be hardwired, and that gives us a way to develop plumbing, wiring, and routing.

**Comment by maparent** [comment]
Basic channel list pages exist; but nobody links to them yet. we probably would want the channel lists to be available in the sidebars? Requires a bit of UX thought. Then we can close this.

**Comment by maparent** [comment]
I would say we have a basic functional UX now. Improvements should be separate tasks.
